FROM python:3.11.14-slim

WORKDIR /app


RUN apt-get update && apt-get install -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY streamlit_app.py .

EXPOSE 8501

CMD [ "streamlit",'run','streamlit_app.py']


